#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config single_monocle true # monocle if single window open

pad=0
barheight=34

bspc config left_padding      $pad
bspc config right_padding     $pad
bspc config top_padding       44
bspc config bottom_padding    $pad

bspc config border_width          0
bspc config window_gap            15
bspc config focus_follows_pointer true
# bspc config ignore_ewmh_fullscreen all
#bspc config focused_border_color \#cc241d
#bspc config normal_border_color \#928374

bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true
#bspc config leaf_monocle         true

bspc rule -a firefox desktop='^2' follow=on focus=on
#bspc rule -a Firefox desktop='^2' # state=floating follow=on
bspc rule -a code-oss desktop='^3'
bspc rule -a discord desktop='^4'
bspc rule -a skype desktop='^4'
bspc rule -a teams desktop='^4'
bspc rule -a TelegramDesktop desktop='^4'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bash /home/sunkengod/.config/polybar/launch.sh --forest &
picom --config ~/.config/picom/ibhagwan/picom.conf &
nitrogen --restore &
setxkbmap -layout "us,ru" -option "grp:alt_shift_toggle" &
/home/sunkengod/.config/scripts/exports.sh &
yay &

